export interface VesselSpec {
  shipName: string
  yearBuilt: string
  classification: string
  portOfRegistry: string
  lightDisplacement: string
  maxDisplacement: string
  callSign: string
  placeBuilt: string
  flag: string
  grtNrtDwt: string
  operationalDisplacement: string
  speed: string
  type: string
  slug: string
}

export const vessels: VesselSpec[] = [
  {
    shipName: "MUTAWA 17",
    yearBuilt: "2023",
    classification: "BUREAU VERITAS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1322.72",
    maxDisplacement: "2922.72",
    callSign: "A6E2381",
    placeBuilt: "China",
    flag: "UAE",
    grtNrtDwt: "1501 T / 450 T / -",
    operationalDisplacement: "1600",
    speed: "13 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-17"
  },
  {
    shipName: "MUTAWA 313",
    yearBuilt: "2012",
    classification: "ABS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1570.22",
    maxDisplacement: "2880.34",
    callSign: "A6E2111",
    placeBuilt: "China",
    flag: "UAE",
    grtNrtDwt: "1678 T / 503 T / 1340 T",
    operationalDisplacement: "1310",
    speed: "13 knots",
    type: "Diving Support Vessel",
    slug: "mutawa-313"
  },
  {
    shipName: "MUTAWA 309",
    yearBuilt: "2011",
    classification: "ABS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1322.72",
    maxDisplacement: "2922.72",
    callSign: "A6E2607",
    placeBuilt: "China",
    flag: "UAE",
    grtNrtDwt: "1674 T / 502 T / 1360 T",
    operationalDisplacement: "1600",
    speed: "13 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-309"
  },
  {
    shipName: "LAND CRAFT SEA PARROT",
    yearBuilt: "2022",
    classification: "BUREAU VERITAS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1213.26",
    maxDisplacement: "2897.32",
    callSign: "A6E2556",
    placeBuilt: "China",
    flag: "UAE",
    grtNrtDwt: "1716 T / 514 T / 1660",
    operationalDisplacement: "1684",
    speed: "10.5 knots",
    type: "Landing Craft",
    slug: "land-craft-sea-parrot"
  },
  {
    shipName: "MUTAWA 9",
    yearBuilt: "2005",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "513",
    maxDisplacement: "1050",
    callSign: "A6E 3016",
    placeBuilt: "Hin Lee Shipyard",
    flag: "UAE",
    grtNrtDwt: "627 / 188 / 550",
    operationalDisplacement: "850",
    speed: "13.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-9"
  },
  {
    shipName: "KHALFAN",
    yearBuilt: "2004",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "911",
    maxDisplacement: "1750",
    callSign: "A6E6954",
    placeBuilt: "Dubai Dry Dock",
    flag: "UAE",
    grtNrtDwt: "1175 / 352 / 838.5",
    operationalDisplacement: "1150",
    speed: "13.0 knots",
    type: "Supply Vessel",
    slug: "khalfan"
  },
  {
    shipName: "FAISAL 1",
    yearBuilt: "2004",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "893",
    maxDisplacement: "1750",
    callSign: "A6E2954",
    placeBuilt: "Dubai Dry Dock",
    flag: "UAE",
    grtNrtDwt: "1175 / 352 / 838",
    operationalDisplacement: "1150",
    speed: "13.0 knots",
    type: "Anchor Handling Tug",
    slug: "faisal-1"
  },
  {
    shipName: "MUTAWA 10",
    yearBuilt: "2005",
    classification: "RINA CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "618",
    maxDisplacement: "1180",
    callSign: "A6E3050",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "499 / 149 / 660",
    operationalDisplacement: "846",
    speed: "12.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-10"
  },
  {
    shipName: "MUTAWA 11",
    yearBuilt: "2008",
    classification: "DNV CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "956",
    maxDisplacement: "1816",
    callSign: "A6E3142",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1060 / 318 / 957",
    operationalDisplacement: "1150",
    speed: "12.0 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-11"
  },
  {
    shipName: "MUTAWA 12",
    yearBuilt: "2010",
    classification: "DNV CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "995",
    maxDisplacement: "1816",
    callSign: "A6E 2762",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1060 / 318 / 957",
    operationalDisplacement: "1150",
    speed: "12 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-12"
  },
  {
    shipName: "MUTAWA 13",
    yearBuilt: "2011",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "976",
    maxDisplacement: "1938",
    callSign: "A6E2231",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1120 / 336 / 962",
    operationalDisplacement: "1100",
    speed: "12.0 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-13"
  },
  {
    shipName: "MUTAWA 101",
    yearBuilt: "2007",
    classification: "DNV CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "836",
    maxDisplacement: "1529",
    callSign: "A6E 3110",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "735 / 220 / 609",
    operationalDisplacement: "1100",
    speed: "12.5 knots",
    type: "Utility Vessel",
    slug: "mutawa-101"
  },
  {
    shipName: "MUTAWA 102",
    yearBuilt: "2010",
    classification: "DNV CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "837",
    maxDisplacement: "1529",
    callSign: "A6E 2176",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "875 / 262 / 609",
    operationalDisplacement: "1100",
    speed: "13.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-102"
  },
  {
    shipName: "MUTAWA 103",
    yearBuilt: "2012",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1018",
    maxDisplacement: "1695",
    callSign: "A6E 2656",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "875 / 262 / 745",
    operationalDisplacement: "1100",
    speed: "13.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-103"
  },
  {
    shipName: "MUTAWA 104",
    yearBuilt: "2016",
    classification: "RINA CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1035",
    maxDisplacement: "1680",
    callSign: "A6E2808",
    placeBuilt: "Guangzhou Shunhai Shipyards Ltd",
    flag: "UAE",
    grtNrtDwt: "1058 / 317 / 645",
    operationalDisplacement: "1126",
    speed: "13.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-104"
  },
  {
    shipName: "MUTAWA 105",
    yearBuilt: "2006",
    classification: "RINA CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "755",
    maxDisplacement: "1750",
    callSign: "J8B3477",
    placeBuilt: "Tuong Aik Shipyard Sdn. Bhd / Malaysia",
    flag: "UAE",
    grtNrtDwt: "716 / 215 / 580",
    operationalDisplacement: "1100",
    speed: "12.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-105"
  },
  {
    shipName: "MUTAWA 106",
    yearBuilt: "2015",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1018",
    maxDisplacement: "1680.7",
    callSign: "A6E2269",
    placeBuilt: "Guangzhou Shunhai Shipyards Ltd",
    flag: "UAE",
    grtNrtDwt: "875 / 262 / 609",
    operationalDisplacement: "1127",
    speed: "13.0 knots",
    type: "Utility Vessel",
    slug: "mutawa-106"
  },
  {
    shipName: "MUTAWA 202",
    yearBuilt: "2011",
    classification: "TASNEEF / DNV",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "52",
    maxDisplacement: "70",
    callSign: "A6E2276",
    placeBuilt: "Dubai",
    flag: "UAE",
    grtNrtDwt: "98 / 30 / 98",
    operationalDisplacement: "-",
    speed: "30 knots max / 25 knots cruising",
    type: "Fast Crew Boat",
    slug: "mutawa-202"
  },
  {
    shipName: "MUTAWA 301",
    yearBuilt: "2012",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1355",
    maxDisplacement: "2451",
    callSign: "A6E2650",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1366 / 409 / 1300",
    operationalDisplacement: "1550",
    speed: "12.0 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-301"
  },
  {
    shipName: "MUTAWA 302",
    yearBuilt: "2011",
    classification: "RINA CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1418",
    maxDisplacement: "2954",
    callSign: "A6E2427",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1390 / 417 / 1200",
    operationalDisplacement: "1580",
    speed: "12.0 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-302"
  },
  {
    shipName: "MUTAWA 303",
    yearBuilt: "2011",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1355",
    maxDisplacement: "2451",
    callSign: "A6E2830",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1260 / 409 / 1300",
    operationalDisplacement: "1550",
    speed: "12 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-303"
  },
  {
    shipName: "MUTAWA 304",
    yearBuilt: "2010",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1100",
    maxDisplacement: "2100",
    callSign: "A6E3014",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1123 / 337 / 700-1000 T",
    operationalDisplacement: "1250",
    speed: "12.0 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-304"
  },
  {
    shipName: "MUTAWA 305",
    yearBuilt: "2011",
    classification: "DNV GL",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1467",
    maxDisplacement: "2258.33",
    callSign: "A6E2220",
    placeBuilt: "Lingshan Shipyard",
    flag: "UAE",
    grtNrtDwt: "1123 / 337 / 791",
    operationalDisplacement: "1973",
    speed: "12.0 knots",
    type: "Offshore Support Vessel",
    slug: "mutawa-305"
  },
  {
    shipName: "MUTAWA 306",
    yearBuilt: "2016",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "1132",
    maxDisplacement: "2340",
    callSign: "A6E2548",
    placeBuilt: "Guangzhou Shunhai Shipyards Ltd, China",
    flag: "UAE",
    grtNrtDwt: "1193 / 353 / 1400",
    operationalDisplacement: "1700",
    speed: "12.5 knots @ 100% MCR",
    type: "Offshore Support Vessel",
    slug: "mutawa-306"
  },
  {
    shipName: "MUTAWA 312",
    yearBuilt: "2010",
    classification: "ABS *A1, Towing Vessel, Offshore Support Vessel, FiFi1",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "-",
    maxDisplacement: "-",
    callSign: "A6E2239",
    placeBuilt: "Guangzhou Panyu Lingshan Shipyard, China",
    flag: "UAE",
    grtNrtDwt: "1396 / 418 / -",
    operationalDisplacement: "-",
    speed: "12.0 knots",
    type: "Towing / Support Vessel",
    slug: "mutawa-312"
  },
  {
    shipName: "MUTAWA 401",
    yearBuilt: "2013",
    classification: "Bureau Veritas",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "2600",
    maxDisplacement: "3978",
    callSign: "A6E 2317",
    placeBuilt: "Guangzhou Shipyard Ltd, China",
    flag: "UAE",
    grtNrtDwt: "2857 / 857 / 1690",
    operationalDisplacement: "3872",
    speed: "12.0 knots @ 80% MCR",
    type: "Diving Support Vessel",
    slug: "mutawa-401"
  },
  {
    shipName: "MUTAWA 402",
    yearBuilt: "2015",
    classification: "DNV CLASS",
    portOfRegistry: "Abu Dhabi",
    lightDisplacement: "2600",
    maxDisplacement: "3978",
    callSign: "A6E 2317",
    placeBuilt: "Guangzhou Hangtong Shipbuilding And Shipping Co. Ltd, China",
    flag: "UAE",
    grtNrtDwt: "2857 T / 1690 / 857",
    operationalDisplacement: "3872",
    speed: "12.0 knots @ 80% MCR",
    type: "Diving Support Vessel",
    slug: "mutawa-402"
  }
]
